CREATE TABLE IF NOT EXISTS b_uni_file_task (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FILE_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'pending',
    ERROR_MESSAGE TEXT,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX IDX_STATUS (STATUS),
    INDEX IDX_CREATED (CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;